name: dreamboard
services:
  - build_command: yarn build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: alexxozo/dreamboard-do
    name: dreamboard
